name: Build/release

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [lts/*]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}